### ISSUE TITLE
(displayed) Image dimensions do not change upon loading a new image

### ISSUE THREAD

**Issue by HarshKhandeparkar** [publiclab/image-sequencer#1391]
### Please describe the problem (or idea)
![Screenshot from 2019-12-25 00-33-09](https://user-images.githubusercontent.com/34770591/71423262-2b3ffc00-26ae-11ea-883e-7d2897376c10.png)
![Screenshot from 2019-12-25 00-33-15](https://user-images.githubusercontent.com/34770591/71423266-2f6c1980-26ae-11ea-9031-cf5690beee97.png)

As can be seen in the above two screenshots, the image dimensions did not change even though a different, rotated image was loaded.

### Please show us where to look

https://beta.sequencer.publiclab.org

### What's your PublicLab.org username?

> This can help us diagnose the issue:

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by HarshKhandeparkar** [comment]
@publiclab/is-reviewers

**Comment by ataata107** [comment]
Can I work on this?

**Comment by HarshKhandeparkar** [comment]
Sure.

**Comment by ataata107** [comment]
The main bug is that onSetup,onComplete functions in defaultHtmlStepUi.js are not called after user loads the image through UI hence the values are not updated.

So I found a method to achieve this which is working locally on my computer

> 1. Add src param to urlhash
> 2  Reloading the page
Because of window.onload function in demo.js as we refresh the window it gets triggered and the sequencer loads the sequence 
But this involves refreshing the page unnecessarily
Could there be any way to call the onSetup,onComplete after loading new images through UI
