### ISSUE TITLE
blob/region detection and extraction for particle analysis

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#172]
region extraction -- https://github.com/linuxenko/rextract.js

This would let us identify objects on images like these:

![imagejsteps.jpg](https://publiclab.org/system/images/photos/000/011/635/original/imagejsteps.jpg)

Read more about this stuff here: https://publiclab.org/tag/particle-imaging

Especially here: https://publiclab.org/notes/mathew/09-19-2015/using-imagej-to-process-passive-particle-monitor-samples

Step-by-step guides to analysis:

https://publiclab.org/notes/SimonPyle/05-13-2016/automating-imagej-for-particle-image-analysis

https://publiclab.org/notes/amirberAgain/01-12-2018/python-and-opencv-to-analyze-microscope-slide-images-of-airborne-particles

**Comment by tech4GT** [comment]
@jywarren i am now taking up this issue can you please elaborate a little what data do we need as output. We can edge detect the image for the particles, do we we need some data about each of the particles like area etc?

**Comment by jywarren** [comment]
Yes, after the several image filtering steps as in this post:

https://publiclab.org/notes/amirberAgain/01-12-2018/python-and-opencv-to-analyze-microscope-slide-images-of-airborne-particles

We'd then want to add to the metadata (and to display in the interface) a count of particles by size - ask AmirberAgain in the above post for some help! 

Excited! Thank you!

**Comment by jywarren** [comment]
But let's solve this in a set of chained modules if possible!

**Comment by tech4GT** [comment]
@jywarren totally, because we already have some of the steps which are needed, this would be better implemented with a set of chained modules
Also, I have an idea from this, we can have an ability to add macros so that users can save a set of most used modules, in browser that can be implemented with the url and in cli we can have a macros.json file and our first macro can be region extraction😁
what say?

**Comment by tech4GT** [comment]
@jywarren also can you please have a look at the proposal for this project since the gsoc deadline is coming and the submission is already started

**Comment by tech4GT** [comment]
@jywarren I have made some progress on this one, So I have decided to follow these steps, please guide me if this seems correct
- First we apply edge-detect to the image to binarize it, We can have a foreground pixel and background pixel associated with the output(Since we decided that image can be on black background as well)
- We can then apply connected component labelling on the edge-detected image(I'll write a new module for this which will take in foreground pixel values and background pixel values and a binary image)
- We can then count the number of pixels in each of the components and that will give us the perimeter in pixels
- For area I have devised a method (but it will not be exact if particles are concave), we can run that for each component and it'll fill each component and then again we can count the number of foreground pixels in each component and get the area in pixels^2 (squared)
- Area and perimeter can be converted using a given scale to actual dimensions.

Algorithm: 
![img_0347](https://user-images.githubusercontent.com/25617855/39107641-37119ea2-46e1-11e8-9974-adb68ff4c7b3.jpg)

**Comment by jywarren** [comment]
Hi! Very cool! I wonder if you could post on the thread with Amir where he
laid out his steps, and check with him if this matches the process he's
described?

**Comment by tech4GT** [comment]
@jywarren Done!! Can you also please have a look at the meta modules issue #200 , I have consolidated ideas and made a checklist, Thanks :)

**Comment by jywarren** [comment]
Found a nice reference for this!!! https://blog.acipo.com/blob-detection-js/

![image](https://user-images.githubusercontent.com/24359/51356118-693ca500-1a87-11e9-9770-52b6c143e07a.png)

**Comment by aashna27** [comment]
Hey I have made some progress to this and I would like further guidance on it! The results that I am getting using opencv in our project are

![resblob](https://user-images.githubusercontent.com/26546120/59780090-0e79d480-92d7-11e9-8dd0-2f138d5cb493.png)

![blobres2](https://user-images.githubusercontent.com/26546120/59780171-35380b00-92d7-11e9-964b-ce76074a0e66.png)

**Comment by jywarren** [comment]
Wow!!!! Amazing!!!!!

**Comment by jywarren** [comment]
I think this is great. My thoughts are:

1. the overall workflow is many steps, as in the documentation in the original issue at top. But we should as much as possible break it into different modules. Let's make a demo sequencer to demonstrate these steps with images from a microscope (at top)
2. let's think about what the final desired output format is, by reading those docs at top. Is it a histogram of the particle size, is it about how round the particles are, how concentrated they are? All the above?

Thanks @aashna27 ! This is so exciting! Eventually we want people to be able to upload their microscope images (from https://publiclab.org/micro kits) and do an analysis, so let's build from distinct modules in that direction!

**Comment by aashna27** [comment]
So I ll upload the code uptill now, wherein we have markers to detect particles in microscopic images.

**Comment by jywarren** [comment]
Great, can you lay out how this initial PR fits into the overall workflow from the posts above?
