### ISSUE TITLE
Halftone angle (in radians) needs to be a decimal instead of an integer

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#1889]
When I try to adjust the angle of a halftone in this sequence: https://sequencer.publiclab.org/examples/#steps=color-halftone{}

The slider will only go to 0 or 1, and I can't set a decimal. I think the type is set incorrectly or perhaps the input step size?

![rads](https://user-images.githubusercontent.com/24359/118191200-38c86400-b412-11eb-8832-b3e53cc68493.gif)

Aha, the input is this:

```html
<input class="form-control target" type="range" name="angle" value="0.25" placeholder="" min="0" max="1.57" step="1">
```

https://github.com/publiclab/image-sequencer/blob/3caa033c8febf5055c28f616b534933c00fcbe65/src/modules/ColorHalftone/info.json#L5-L12

this shows it should be a float, but i think we need to set the "step" in the options too:

https://github.com/publiclab/image-sequencer/blob/3caa033c8febf5055c28f616b534933c00fcbe65/examples/lib/defaultHtmlStepUi.js#L132-L141

So maybe if we add a `step` param to the info.json of the color halftone module, this'll work?

**Comment by waridrox** [comment]
> So maybe if we add a step param to the info.json of the color halftone module, this'll work?

I think it might work. Will take a look at this soon...

**Comment by waridrox** [comment]
Hey @jywarren, I think the module already has the `step` parameter to account for the variable angle 😅. Maybe the changes are not yet pushed to the stable version release then...🤔

https://github.com/publiclab/image-sequencer/blob/86115fcc88225c907fefd92762e60042c93f73c5/src/modules/ColorHalftone/info.json#L6-L13

That's because the module works perfectly on the local dev env: 


https://user-images.githubusercontent.com/58583793/118222589-850cb600-b49d-11eb-8de1-a56e1d06eb56.mp4

**Comment by jywarren** [comment]
Ack! Good catch! I knew I was having deja vu while writing that issue.... !!
