### ISSUE TITLE
Filetype extraction

### ISSUE THREAD

**Issue by ccpandhare** [publiclab/image-sequencer#19]
Some modules might require the filetype.
I hadn't noticed that `options.format` is undefined, so:
```
options.format = options.format || "jpg";
```
always results in `options.format` to be equal to `jpg`.
Also, we can't only rely on extension of the file. For example, a jpg file renamed as png would work perfectly fine otherwise, but when we set the src for img, we do:
```
img.src = 'data:image/' + options.format + ';base64,' + buffer.read().toString();
```
so this might result in a faulty image.
Should we import the module [file-type](https://www.npmjs.com/package/file-type)?

**Comment by jywarren** [comment]
Sure, that sounds good. As much auto-detection as possible is a good idea,
but we can also set a default (png?) since the images will be transcribed
to a canvas in many modules, and so the encoding won't be preserved
anyways. Some of this will start to affect our ideas about using diff
algorithms to quantify module behavior... colors will start to drift
slightly, etc. but the diff modules I've seen typically specify a
"tolerance" to account for this.

**Comment by ccpandhare** [comment]
We should think about it.
Actually I was thinking of finding the file-type everytime we export the image as a data URL.
Because everything else is fine but
```
data:image/wrongformat;base64,...
```
Can be problematic.
