### ISSUE TITLE
Patch on delete a sequence after crop

### ISSUE THREAD

**Issue by Paarmita** [publiclab/image-sequencer#352]
There occurs a black patch when we delete the crop sequence.

Issue can be reproduced like this

![aaa ogv](https://user-images.githubusercontent.com/26546816/46241158-61220200-c3d1-11e8-9c5e-bf9652f2eceb.gif)

**Comment by Ankit-Singla** [comment]
@tech4GT @jywarren Take a look at this. The patch stays until and unless a there is a click in the grey of the patch, and also renders the part of the UI it overlaps inaccessible/unresponsive.
Good observation @Paarmita 
I would like to give it a try, if that's okay.

**Comment by Paarmita** [comment]
@Ankit-Singla Go for it :+1: You need to see the files to be changed for this bug.

**Comment by tech4GT** [comment]
@Ankit-Singla Actually I am aware of this issue and last I checked this was an issue with the library `Image-area-select` that we for the selection feature. Maybe you can solve some smaller issues first to familiarize yourself with the code a little more before diving into this one, what say? Thanks!

**Comment by VibhorCodecianGupta** [comment]
@tech4GT #590 resolves this. The fix is a workaround since the plugin itself is buggy. Upon observation, the divs with classes `imgareaselect-*` are the ones that always remained, so I added custom js to handle removing those divs from the DOM itself when the remove function is called. Works well for now.
