### ISSUE TITLE
Uncaught TypeError: parseCoordInputs.parseCornerCoordinateInputs is not a function

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer#606]
https://github.com/publiclab/image-sequencer/blob/35f7605a248ac99371650503a31b27ebd00c09a6/src/modules/Overlay/Module.js#L18

Hi @Divy123, i'm seeing an error as above in this line - strangely, this line was compiled into the `/dist/` folder instead of being browserified:

```js
    var parseCoordInputs = require('../../util/ParseInputCoordinates');
```

So of course it can't do require in the browser. Do you know what's going on? Related to PR https://github.com/publiclab/image-sequencer/pull/592

Thank you!

A bit of urgency because this is deployed to the demo already, affects Crop and Overlay modules.

**Comment by Divy123** [comment]
Sure @jywarren. I am travelling right now.
Will definitely look into in 3-4 hours.

**Comment by VibhorCodecianGupta** [comment]
@jywarren @Divy123 It's an easy fix. The issue lies with the fact that the function was exported via `module.exports` which exports references, so the variable which stores the `require` can itself be called as a function because the function exported is stored there. `parseCoordInputs.parseCornerCoordinateInputs` doesn't exist, basically.
