### ISSUE TITLE
Exposure module

### ISSUE THREAD

**Issue by kindanduseful** [publiclab/image-sequencer#612]
Exposure is different from brightness -- not sure how! But a separate Exposure module would be nice, thank you!

**Comment by aashna27** [comment]
@jywarren could you please have a look at it and then I would like to work on it.

**Comment by jywarren** [comment]
This is a great idea. Might take some research!

**Comment by aashna27** [comment]
Yepp.. would do 😊

**Comment by HarshKhandeparkar** [comment]
@aashna27 from what I know about this stuff, I think exposure is the amount of light entering the lens of a camera. Increase in exposure means that more light is going to enter the lens and photos in the night are going to look better and visibility will increase but with brightness the photo is only going to look brighter. If this issue is about the same exposure then I think this might not be possible digitally as it s a physical thing. Correct me if I'm wrong. @jywarren @kindanduseful

**Comment by HarshKhandeparkar** [comment]
Ah I just found some info [here](https://www.cambridgeincolour.com/tutorials/camera-exposure.htm) it days that exposure depends upon physical factors such as aperture of the lens

**Comment by aashna27** [comment]
Yess this gets changed with aperture and other camera lens factors, I
searched. It didn't seem feasible to me.

**Comment by HarshKhandeparkar** [comment]
So can this issue be closed as this is not possible?
