### ISSUE TITLE
White balance acting strangely (let's rename to Color Temperature)

### ISSUE THREAD

**Issue by kindanduseful** [publiclab/image-sequencer#613]
Not sure if this is supposed to happen, but I got this with white balance:

![image](https://user-images.githubusercontent.com/18472957/50729313-b32b9f80-1105-11e9-8c34-47417ad18bbd.png)

Is it an error?

**Comment by VibhorCodecianGupta** [comment]
@kindanduseful Thanks for bringing this up, I was thinking of making a PR to change the module name to `Colour Temperature` instead of `White Balance`, because this module indeed is more of a colour temperature based image processor. This behaviour is expected, you can read up about images with colour temperatures, wherein certain colour channels are enhanced drastically based on the temperatures.

What you can do, is change the name of this module to `Colour Temperature` instead. 
@jywarren thoughts?

**Comment by VibhorCodecianGupta** [comment]
Yes, working on it. Will open a PR soon!

**Comment by aashna27** [comment]
@VibhorCodecianGupta are you making a new white balance module ?

**Comment by VibhorCodecianGupta** [comment]
@aashna27 Yep! based on the brightest pixel in the image

**Comment by aashna27** [comment]
> @aashna27 Yep! based on the brightest pixel in the image
okay !! good to know 😄

**Comment by HarshKhandeparkar** [comment]
The original issue is open

**Comment by jywarren** [comment]
Hi @HarshKhandeparkar i think i'm going to reopen this and rename it to something like `change the module name to Colour Temperature instead of White Balance` as @VibhorCodecianGupta suggested, and we can try to revive the original white balance issue too?

**Comment by HarshKhandeparkar** [comment]
Vibhor is actually working on the old white balance issue so we don't have to revive it.
